# 性能配置
performance:
  async_mode: true          # 是否启用异步模式
  buffer_size: 8388608      # 读取缓冲区大小(8MB)
  use_mmap: true           # 是否使用mmap处理大文件
  thread_count: 4          # 线程池大小

# 哈希算法配置
algorithms:
  MD5:
    enabled: true
    compare_format: "{filename}: {value}"
  SHA1:
    enabled: true
    compare_format: "{filename}: {value}"
  SHA256:
    enabled: true
    compare_format: "{filename}: {value}"
  SHA3_256:
    enabled: true
    compare_format: "{filename}: {value}"
  BLAKE2b:
    enabled: true
    compare_format: "{filename}: {value}"
  SHA384:
    enabled: false
    compare_format: "{filename}: {value}"
  SHA3_384:
    enabled: false
    compare_format: "{filename}: {value}"
  SHA512:
    enabled: false
    compare_format: "{filename}: {value}"

# 比较模式配置
comparison:
  match_message: "******✅ 所有文件哈希值相同******"
  mismatch_message: "******⚠️ 存在不一致的哈希值******"
  detail_format: "{file1} 与 {file2} 的 {algo} 值不同"

# 输出配置
output:
  color: true              # 启用彩色输出
  progress_bar: true       # 显示进度条
  show_time: true         # 显示处理时间
  format: "default"        # 输出格式(default/json/csv)

# 文件处理
file_handling:
  recursive: false         # 是否递归扫描子目录
  retry_count: 3          # 文件读取失败重试次数
  ignore_errors: false    # 是否忽略错误继续执行

# 排除模式
exclude_patterns:
  - "*.tmp"
  - "*.temp"
  - "~*"

# 日志配置
logging:
  enabled: true
  level: "INFO"
  file: "hash_calculator.log"
